#!/usr/bin/env python3
"""
IT General Controls (ITGC) Design Workbook + Compliance Status Dashboard
==============================================================================
Renders the full SOX ITGC catalog (see itgc_catalog.py) as an audit-ready
design workbook, plus a point-in-time implementation/testing status per
control and a rolled-up compliance status dashboard (RAG by control, design
vs. operating-effectiveness testing coverage, overall audit readiness %).

Outputs
-------
  outputs/it-controls-design.xlsx   (Control Design + Dashboard + Legend sheets)
  outputs/it-controls-design.md

Run:  python3 sox/it-general-controls.py
"""

from __future__ import annotations

import os
import sys

from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.styles import Alignment, Font, PatternFill

sys.path.insert(0, os.path.dirname(__file__))
from itgc_catalog import CATALOG  # noqa: E402
from xlsx_style import (  # noqa: E402
    HEADER_FILL, HEADER_FONT, RISK_FILL, RISK_FONT_COLOR, STATUS_FILL, add_table,
    autosize_columns, style_data_rows, style_header_row, style_title_block, write_legend_sheet,
)

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "outputs")
os.makedirs(OUT_DIR, exist_ok=True)

RISK_DEFINITIONS = {
    "Low": "Design and operating effectiveness confirmed; monitor via routine review cycle.",
    "Medium": "Control operating; minor design or evidence gaps being closed this quarter.",
    "High": "Control partially implemented or not yet operating-effectiveness tested.",
    "Critical": "Control gap represents likely exposure to a material weakness if unremediated.",
}

# control_id -> (implementation_status, design_tested, operating_tested, last_review_date)
STATUS = {
    "SOX-ITGC-001": ("Implemented", "Yes", "Yes", "2026-07-15"),
    "SOX-ITGC-002": ("Implemented", "Yes", "No", "2026-07-15"),
    "SOX-ITGC-003": ("In Progress", "Yes", "No", "2026-06-20"),
    "SOX-ITGC-004": ("In Progress", "No", "No", "2026-05-10"),
    "SOX-ITGC-005": ("Implemented", "Yes", "Yes", "2026-07-30"),
    "SOX-ITGC-006": ("Implemented", "Yes", "Yes", "2026-07-01"),
    "SOX-ITGC-007": ("In Progress", "Yes", "No", "2026-06-15"),
    "SOX-ITGC-008": ("In Progress", "No", "No", "2026-05-01"),
    "SOX-ITGC-009": ("Implemented", "Yes", "Yes", "2026-07-20"),
}

HEADERS = ["Control ID", "Control Title", "Domain", "ITGC Area", "Description", "Control Owner",
           "Control Type", "Frequency", "Automation Level", "Risk Rating",
           "Implementation Status", "Design Tested", "Operating Tested", "Last Reviewed"]


def build_design_sheet(wb):
    ws = wb.active
    ws.title = "ITGC Design"
    ws.sheet_view.showGridLines = False

    header_row = style_title_block(
        ws,
        "IT General Controls — Design Workbook",
        "SOX Compliance Package | Confidential - Internal Use | Generated by it-general-controls.py",
        n_cols=len(HEADERS),
    )
    for col, h in enumerate(HEADERS, start=1):
        ws.cell(row=header_row, column=col, value=h)
    style_header_row(ws, header_row, len(HEADERS))

    r = header_row + 1
    first_data_row = r
    for c in CATALOG:
        impl, design, operating, reviewed = STATUS[c.control_id]
        ws.cell(row=r, column=1, value=c.control_id)
        ws.cell(row=r, column=2, value=c.title)
        ws.cell(row=r, column=3, value=c.domain)
        ws.cell(row=r, column=4, value=c.itgc_domain_tag)
        ws.cell(row=r, column=5, value=c.description)
        ws.cell(row=r, column=6, value=c.control_owner)
        ws.cell(row=r, column=7, value=c.control_type)
        ws.cell(row=r, column=8, value=c.frequency)
        ws.cell(row=r, column=9, value=c.automation)
        ws.cell(row=r, column=10, value=c.risk_rating)
        ws.cell(row=r, column=11, value=impl)
        ws.cell(row=r, column=12, value=design)
        ws.cell(row=r, column=13, value=operating)
        ws.cell(row=r, column=14, value=reviewed)
        r += 1
    last_data_row = r - 1

    style_data_rows(ws, first_data_row, last_data_row, len(HEADERS),
                     risk_col=10, status_col=11)
    autosize_columns(ws, {1: 14, 2: 40, 3: 20, 4: 16, 5: 56, 6: 30, 7: 16, 8: 26,
                           9: 22, 10: 12, 11: 16, 12: 12, 13: 14, 14: 13})
    add_table(ws, "ITGCDesign", f"A{header_row}:N{last_data_row}")
    return ws


def build_dashboard_sheet(wb):
    ws = wb.create_sheet("Dashboard")
    ws.sheet_view.showGridLines = False
    ws["A1"] = "SOX ITGC — Compliance Status Dashboard"
    ws["A1"].font = Font(size=16, bold=True, color="1F3864")
    ws.merge_cells("A1:D1")
    total = len(CATALOG)
    implemented = sum(1 for c in CATALOG if STATUS[c.control_id][0] == "Implemented")
    design_tested = sum(1 for c in CATALOG if STATUS[c.control_id][1] == "Yes")
    operating_tested = sum(1 for c in CATALOG if STATUS[c.control_id][2] == "Yes")
    readiness_pct = round(100 * operating_tested / total)
    ws["A2"] = (f"As of 2026-08-21  |  {total} ITGCs  |  {implemented}/{total} implemented  |  "
                f"{operating_tested}/{total} operating-effectiveness tested  |  "
                f"Audit readiness: {readiness_pct}%")
    ws["A2"].font = Font(italic=True, color="595959")
    ws.merge_cells("A2:D2")

    # Implementation status breakdown + chart
    row = 4
    ws.cell(row=row, column=1, value="Implementation Status").font = HEADER_FONT
    ws.cell(row=row, column=1).fill = HEADER_FILL
    ws.cell(row=row, column=2, value="Count").font = HEADER_FONT
    ws.cell(row=row, column=2).fill = HEADER_FILL
    statuses = ["Implemented", "In Progress", "Planned", "Not Started"]
    counts = {s: sum(1 for c in CATALOG if STATUS[c.control_id][0] == s) for s in statuses}
    start_row = row + 1
    for i, s in enumerate(statuses):
        rr = start_row + i
        c1 = ws.cell(row=rr, column=1, value=s)
        if s in STATUS_FILL:
            c1.fill = PatternFill("solid", fgColor=STATUS_FILL[s])
        c2 = ws.cell(row=rr, column=2, value=counts[s])
        c2.alignment = Alignment(horizontal="center")
    end_row = start_row + len(statuses) - 1

    chart = BarChart()
    chart.title = "ITGCs by Implementation Status"
    chart.y_axis.title = "Count"
    chart.x_axis.title = "Status"
    data = Reference(ws, min_col=2, min_row=row, max_row=end_row)
    cats = Reference(ws, min_col=1, min_row=start_row, max_row=end_row)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.width, chart.height = 14, 8
    ws.add_chart(chart, "D4")

    # Risk rating breakdown
    risk_row = end_row + 3
    ws.cell(row=risk_row, column=1, value="Risk Rating").font = HEADER_FONT
    ws.cell(row=risk_row, column=1).fill = HEADER_FILL
    ws.cell(row=risk_row, column=2, value="Count").font = HEADER_FONT
    ws.cell(row=risk_row, column=2).fill = HEADER_FILL
    risk_counts = {lvl: sum(1 for c in CATALOG if c.risk_rating == lvl)
                   for lvl in ["Critical", "High", "Medium", "Low"]}
    for i, lvl in enumerate(["Critical", "High", "Medium", "Low"]):
        rr = risk_row + 1 + i
        c1 = ws.cell(row=rr, column=1, value=lvl)
        c1.fill = PatternFill("solid", fgColor=RISK_FILL[lvl])
        c1.font = Font(bold=True, color=RISK_FONT_COLOR[lvl])
        c2 = ws.cell(row=rr, column=2, value=risk_counts[lvl])
        c2.alignment = Alignment(horizontal="center")

    # Per-control RAG status table
    rag_row = risk_row + 7
    rag_headers = ["Control ID", "Title", "Design Tested", "Operating Tested", "RAG"]
    for col, h in enumerate(rag_headers, start=1):
        ws.cell(row=rag_row, column=col, value=h).font = HEADER_FONT
        ws.cell(row=rag_row, column=col).fill = HEADER_FILL
    r = rag_row + 1
    first_rag_row = r
    for c in CATALOG:
        impl, design, operating, _ = STATUS[c.control_id]
        rag = "Green" if operating == "Yes" else ("Amber" if design == "Yes" else "Red")
        ws.cell(row=r, column=1, value=c.control_id)
        ws.cell(row=r, column=2, value=c.title)
        ws.cell(row=r, column=3, value=design)
        ws.cell(row=r, column=4, value=operating)
        rag_cell = ws.cell(row=r, column=5, value=rag)
        rag_fill = {"Green": "C6E0B4", "Amber": "FFE699", "Red": "F4B183"}[rag]
        rag_cell.fill = PatternFill("solid", fgColor=rag_fill)
        rag_cell.alignment = Alignment(horizontal="center")
        r += 1
    autosize_columns(ws, {1: 22, 2: 44, 3: 16, 4: 16, 5: 10})

    return ws


def write_markdown(path: str):
    total = len(CATALOG)
    implemented = sum(1 for c in CATALOG if STATUS[c.control_id][0] == "Implemented")
    operating_tested = sum(1 for c in CATALOG if STATUS[c.control_id][2] == "Yes")
    readiness_pct = round(100 * operating_tested / total)

    lines = [
        "# IT General Controls — Design Workbook",
        "",
        "*SOX Compliance Package | Confidential - Internal Use*",
        "",
        f"**{total} ITGCs.** {implemented}/{total} implemented, {operating_tested}/{total} "
        f"operating-effectiveness tested. Audit readiness: **{readiness_pct}%**.",
        "",
        "| Control ID | Title | Domain | Owner | Type | Frequency | Risk | Status | Design Tested | Operating Tested |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for c in CATALOG:
        impl, design, operating, reviewed = STATUS[c.control_id]
        lines.append(
            f"| {c.control_id} | {c.title} | {c.domain} | {c.control_owner} | {c.control_type} | "
            f"{c.frequency} | **{c.risk_rating}** | {impl} | {design} | {operating} |"
        )
    lines += ["", "## Control Detail", ""]
    for c in CATALOG:
        impl, design, operating, reviewed = STATUS[c.control_id]
        lines.append(f"### {c.control_id}: {c.title}")
        lines.append(f"- **Domain:** {c.domain} ({c.itgc_domain_tag})")
        lines.append(f"- **Description:** {c.description}")
        lines.append(f"- **Owner:** {c.control_owner} | **Type:** {c.control_type} | "
                      f"**Frequency:** {c.frequency} | **Automation:** {c.automation}")
        lines.append(f"- **Risk Rating:** {c.risk_rating} | **COSO Principles:** "
                      f"{', '.join(c.coso_principles)}")
        lines.append(f"- **Implementation Status:** {impl} | **Design Tested:** {design} | "
                      f"**Operating Tested:** {operating} | **Last Reviewed:** {reviewed}")
        lines.append("")
    lines += ["## Risk Rating Legend", ""]
    for level, definition in RISK_DEFINITIONS.items():
        lines.append(f"- **{level}**: {definition}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    wb = Workbook()
    build_design_sheet(wb)
    build_dashboard_sheet(wb)
    write_legend_sheet(wb, RISK_DEFINITIONS)

    xlsx_path = os.path.join(OUT_DIR, "it-controls-design.xlsx")
    wb.save(xlsx_path)
    md_path = os.path.join(OUT_DIR, "it-controls-design.md")
    write_markdown(md_path)
    print(f"Wrote {xlsx_path}")
    print(f"Wrote {md_path}")
    implemented = sum(1 for c in CATALOG if STATUS[c.control_id][0] == "Implemented")
    print(f"{len(CATALOG)} ITGCs: {implemented} implemented")


if __name__ == "__main__":
    main()
