#!/usr/bin/env python3
"""
ITGC Control Design Template Generator
============================================
Produces a blank, reusable IT General Control design workbook that other
teams or organizations can copy and fill in for their own SOX ITGC catalog.
Unlike sox/it-general-controls.py, this workbook ships with no pre-filled
rows — only headers, instructions, data-validation dropdowns, and a worked
example.

Output
------
  templates/control-design-template.xlsx

Run:  python3 templates/generate-control-template.py
"""

from __future__ import annotations

import os
import sys

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from openpyxl.worksheet.datavalidation import DataValidation

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "sox"))
from xlsx_style import (  # noqa: E402
    add_table, autosize_columns, style_data_rows, style_header_row, style_title_block,
)

OUT_PATH = os.path.join(os.path.dirname(__file__), "control-design-template.xlsx")

HEADERS = ["Control ID", "Control Title", "Domain", "ITGC Area", "Description", "Control Owner",
           "Control Type", "Frequency", "Automation Level", "COSO Principle(s)", "Risk Rating",
           "Implementation Status", "Design Tested", "Operating Tested", "Last Reviewed"]

EXAMPLE_ROW = [
    "SOX-ITGC-XXX", "User Access Provisioning (New Hire / Role Change)", "Access Management",
    "Authorization",
    "New user access to in-scope financial systems is requested, approved by the system/data "
    "owner prior to provisioning, and provisioned strictly per the approved request.",
    "IT Security / IAM Team", "Preventive", "Continuous (event-driven)", "IT-Dependent Manual",
    "P3, P5, P10, P11", "High", "Implemented", "Yes", "Yes", "2026-11-01",
]

DOMAINS = ["Access Management", "Segregation of Duties", "Access Reviews", "Change Management", "Monitoring"]
ITGC_AREAS = ["Authorization", "Change Management", "Access Reviews", "Monitoring"]
CONTROL_TYPES = ["Preventive", "Detective", "Corrective", "Preventive/Detective", "Detective/Corrective"]
AUTOMATION_LEVELS = ["Automated", "IT-Dependent Manual", "Manual"]
STATUSES = ["Not Started", "Planned", "In Progress", "Implemented", "Not Applicable"]
RISK_LEVELS = ["Low", "Medium", "High", "Critical"]
YES_NO = ["Yes", "No"]


def add_dropdown(ws, col_letter: str, options: list[str], first_row: int, last_row: int):
    dv = DataValidation(type="list", formula1=f'"{",".join(options)}"', allow_blank=True)
    dv.error = "Please select a value from the dropdown list."
    dv.errorTitle = "Invalid entry"
    ws.add_data_validation(dv)
    dv.add(f"{col_letter}{first_row}:{col_letter}{last_row}")


def build_workbook() -> Workbook:
    wb = Workbook()
    ws = wb.active
    ws.title = "Control Design Template"
    ws.sheet_view.showGridLines = False

    header_row = style_title_block(
        ws,
        "SOX ITGC Control Design Template",
        "Copy this workbook and populate one row per control in your organization's SOX IT "
        "General Control catalog. Dropdowns are pre-configured for Domain, ITGC Area, Type, "
        "Automation, Status, Risk, and Tested columns. Generated by "
        "templates/generate-control-template.py",
        n_cols=len(HEADERS),
    )
    for col, h in enumerate(HEADERS, start=1):
        ws.cell(row=header_row, column=col, value=h)
    style_header_row(ws, header_row, len(HEADERS))

    example_row_num = header_row + 1
    for col, val in enumerate(EXAMPLE_ROW, start=1):
        ws.cell(row=example_row_num, column=col, value=val)
        ws.cell(row=example_row_num, column=col).font = Font(italic=True, color="808080")

    last_blank_row = example_row_num + 40  # 40 blank rows ready for data entry
    style_data_rows(ws, example_row_num, last_blank_row, len(HEADERS),
                     risk_col=11, status_col=12)

    add_dropdown(ws, "C", DOMAINS, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "D", ITGC_AREAS, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "G", CONTROL_TYPES, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "I", AUTOMATION_LEVELS, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "K", RISK_LEVELS, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "L", STATUSES, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "M", YES_NO, example_row_num + 1, last_blank_row)
    add_dropdown(ws, "N", YES_NO, example_row_num + 1, last_blank_row)

    autosize_columns(ws, {1: 14, 2: 38, 3: 20, 4: 16, 5: 50, 6: 28, 7: 18,
                           8: 24, 9: 20, 10: 18, 11: 12, 12: 16, 13: 12, 14: 14, 15: 13})
    add_table(ws, "ControlTemplate", f"A{header_row}:O{last_blank_row}")

    instructions = wb.create_sheet("Instructions")
    instructions.sheet_view.showGridLines = False
    instructions["A1"] = "How to Use This Template"
    instructions["A1"].font = Font(size=16, bold=True, color="1F3864")
    instructions.merge_cells("A1:B1")
    steps = [
        ("1. Copy this workbook", "Save a copy per business unit, subsidiary, or assessment "
         "cycle; do not edit the master template directly."),
        ("2. Assign Control IDs", "Use a consistent prefix (e.g. SOX-ITGC-001) so controls can "
         "be cross-referenced from the COSO mapping, test procedures, and evidence matrix."),
        ("3. One row per control", "Each control should map to at least one COSO 2013 "
         "principle and one ITGC area (Authorization, Change Management, Access Reviews, "
         "Monitoring)."),
        ("4. Use the dropdowns", "Domain, ITGC Area, Type, Automation, Risk, and Status "
         "columns are data-validated — free text outside the list will trigger a warning."),
        ("5. Review cadence", "Set a Last Reviewed date for every control; High/Critical risk "
         "controls should be tested at minimum quarterly."),
        ("6. Keep it linked", "Reference this catalog's Control IDs from your test-procedure "
         "and evidence-matrix workbooks so the full package stays traceable to one source."),
    ]
    row = 3
    for title, body in steps:
        c1 = instructions.cell(row=row, column=1, value=title)
        c1.font = Font(bold=True)
        c1.alignment = Alignment(vertical="top")
        c2 = instructions.cell(row=row, column=2, value=body)
        c2.alignment = Alignment(wrap_text=True, vertical="top")
        row += 2
    autosize_columns(instructions, {1: 24, 2: 70})

    return wb


def main():
    wb = build_workbook()
    wb.save(OUT_PATH)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
